# Site settings
baseurl = "https://example.com"
languageCode = "en-us"
sectionPagesMenu = "main"
theme = "frances"

[params]
	name = "Karol's Blog'"
	description = "Art Gallery"
	email = "frances@hodgkins.io"
	author = "Karol Sobkowicz"